server:
  port: 9092
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Question-services
    username: postgres
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: Question-service
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
