server:
  port: 9093
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Answer-service
    username: postgres
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true